name: my first workflow
on: workflow_dispatch

jobs:
  first_job:
    runs-on: windows-latest
    steps:
      - name: Print Hello
        run: echo "Hi!"
      - name: Print bye
        run: echo "bye!"
